# Generated by Django 3.1 on 2020-09-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='image',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
