# Generated by Django 3.1 on 2020-09-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200908_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='Здесь будет превью, когда вы добавите файл', upload_to='', verbose_name='Фотография'),
        ),
    ]
